a = float(input("Nhập a: "))
b = float(input("Nhập b: "))

print("Tổng =", a + b)
print("Hiệu =", a - b)
print("Tích =", a * b)
print("Thương =", a / b)
print("Lũy thừa a^b =", a ** b)
print("Chia lấy phần nguyên =", a // b)
print("Chia lấy phần dư =", a % b)
